name: weatherapp
description: "Weatherapp with Bloc logic"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  weather_animation: ^1.0.1
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  http: ^1.1.0
  equatable: ^2.0.5
  flutter_launcher_icons: ^0.13.1

# flutter_launcher_icons:
#   #  image_path: "assets/images/icon-128x128.png"
#   image_path_android: "assets/images/icon-710x599-android.png"
#   image_path_ios: "assets/home.png"
#   android: true # can specify file name here e.g. "ic_launcher"
#   ios: true # can specify file name here e.g. "My-Launcher-Icon"
#   adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
#   adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
#   adaptive_icon_monochrome: "assets/images/icon-monochrome-432x432.png" # only available for Android 13 devices and above
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   remove_alpha_ios: true
#   background_color_ios: "#ffffff"
  





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
flutter:
  uses-material-design: true
  assets:
    - assets/
